<?php
$sources = [
    'ProxyMTProto_tel',
    'GlypeX',
    'mitivpn',
    'proxymaann',
    'mtpro_xyz',
    'jackalproxy',
    'Lion_MTProto',
    'ProxyMTProto',
    'FarahProxy',
    'Myporoxy',
    'irproxy',
    'Proxy_fier',
    'TelMTProto',
    'PlusMTProto',
    'MTP_roto',
    'ProxyHagh',
    'NextGenProxy',
    'proxyhubs',
    'ProxyDaemi',
    'proxyme',
    'frrenett',
    'proxytelegram',
    'we2wayanon',
    'c/1796213998/108613',
    'vpnv2r4y',
    'proxyme',
    'Melli_Config'
    ];

?>
